/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./CipherGift.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { CipherGift } from "~~/contracts/CipherGift";`
 */
import { CipherGift as CipherGift_LOCAL } from "./CipherGift.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0x1BFE706fC87B8C4Fef962b1a275586769FAD746E",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_vault",
            type: "address",
            internalType: "contract ConfidentialETHVault",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "acceptOwnership",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowlistRoot",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claim",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimTargeted",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "salt",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "slotIndex",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "proof",
            type: "bytes32[]",
            internalType: "bytes32[]",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimWithPassword",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "password",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimed",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimedAmount",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "closeAndRefund",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "createPacket",
        inputs: [
          {
            name: "ptype",
            type: "uint8",
            internalType: "enum CipherGift.PacketType",
          },
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "totalProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "totalShares",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "maxShareScalar",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "merkleRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createPacketWithAsset",
        inputs: [
          {
            name: "assetId",
            type: "address",
            internalType: "address",
          },
          {
            name: "ptype",
            type: "uint8",
            internalType: "enum CipherGift.PacketType",
          },
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "totalProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "totalShares",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "maxShareScalar",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "merkleRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createPasswordPacket",
        inputs: [
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "totalProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "totalShares",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "passwordSecret",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createPasswordPacketWithAsset",
        inputs: [
          {
            name: "assetId",
            type: "address",
            internalType: "address",
          },
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "totalProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "totalShares",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "passwordSecret",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createTargetedPacket",
        inputs: [
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encSlotAmounts",
            type: "bytes32[]",
            internalType: "externalEuint64[]",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "merkleRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createTargetedPacketWithAsset",
        inputs: [
          {
            name: "assetId",
            type: "address",
            internalType: "address",
          },
          {
            name: "encTotal",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "encSlotAmounts",
            type: "bytes32[]",
            internalType: "externalEuint64[]",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "expirySecs",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "merkleRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "defaultAssetId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEqualShare",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPacket",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "createdAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "expiresAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "packetType",
            type: "uint8",
            internalType: "enum CipherGift.PacketType",
          },
          {
            name: "totalShares",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "claimedCount",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "maxShareScalar",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "note",
            type: "string",
            internalType: "string",
          },
          {
            name: "refunded",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPacketAsset",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getRemainingAmount",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getSlotAmount",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "slotIndex",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "packetCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "passwordHash",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pause",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "paused",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingOwner",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "previewAllowlistLeaf",
        inputs: [
          {
            name: "salt",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "claimer",
            type: "address",
            internalType: "address",
          },
          {
            name: "slotIndex",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "reveal",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "revealFor",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "claimer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "revealed",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "setAssetVault",
        inputs: [
          {
            name: "assetId",
            type: "address",
            internalType: "address",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "slotAmount",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "",
            type: "uint32",
            internalType: "uint32",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "supportedAssetVault",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unpause",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "vault",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract ConfidentialETHVault",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "event",
        name: "AssetVaultSet",
        inputs: [
          {
            name: "assetId",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "enabled",
            type: "bool",
            indexed: false,
            internalType: "bool",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "OwnershipTransferStarted",
        inputs: [
          {
            name: "previousOwner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "newOwner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
          {
            name: "previousOwner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "newOwner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PacketAssetBound",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "assetId",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PacketClaimed",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "claimer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PacketCreated",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "creator",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "ptype",
            type: "uint8",
            indexed: false,
            internalType: "enum CipherGift.PacketType",
          },
          {
            name: "totalShares",
            type: "uint32",
            indexed: false,
            internalType: "uint32",
          },
          {
            name: "expiresAt",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PacketRefunded",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PacketRevealed",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "claimer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Paused",
        inputs: [
          {
            name: "by",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Unpaused",
        inputs: [
          {
            name: "by",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "AllShareClaimed",
        inputs: [],
      },
      {
        type: "error",
        name: "AlreadyClaimed",
        inputs: [],
      },
      {
        type: "error",
        name: "AlreadyRevealed",
        inputs: [],
      },
      {
        type: "error",
        name: "EmptyShareCount",
        inputs: [],
      },
      {
        type: "error",
        name: "ExpiryInPast",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidPacketId",
        inputs: [],
      },
      {
        type: "error",
        name: "NotAllowlisted",
        inputs: [],
      },
      {
        type: "error",
        name: "NotClaimed",
        inputs: [],
      },
      {
        type: "error",
        name: "NotCreator",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "NotPendingOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "NoteTooLong",
        inputs: [],
      },
      {
        type: "error",
        name: "PacketExpired",
        inputs: [],
      },
      {
        type: "error",
        name: "PacketNotExpired",
        inputs: [],
      },
      {
        type: "error",
        name: "PacketRefunded_",
        inputs: [],
      },
      {
        type: "error",
        name: "PasswordNeedsSecret",
        inputs: [],
      },
      {
        type: "error",
        name: "PasswordRequired",
        inputs: [],
      },
      {
        type: "error",
        name: "Paused_",
        inputs: [],
      },
      {
        type: "error",
        name: "RandomNeedsMaxShare",
        inputs: [],
      },
      {
        type: "error",
        name: "RevealOnlyBlindPackets",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "SlotIndexOutOfRange",
        inputs: [],
      },
      {
        type: "error",
        name: "TargetedNeedsAllowlist",
        inputs: [],
      },
      {
        type: "error",
        name: "TargetedRequiresProof",
        inputs: [],
      },
      {
        type: "error",
        name: "TargetedSlotCountMismatch",
        inputs: [],
      },
      {
        type: "error",
        name: "TargetedUseDedicatedCreate",
        inputs: [],
      },
      {
        type: "error",
        name: "UnexpectedAllowlistRoot",
        inputs: [],
      },
      {
        type: "error",
        name: "UnexpectedMaxShare",
        inputs: [],
      },
      {
        type: "error",
        name: "UnexpectedPasswordSecret",
        inputs: [],
      },
      {
        type: "error",
        name: "UnsupportedAsset",
        inputs: [],
      },
      {
        type: "error",
        name: "UseClaimForOpenPackets",
        inputs: [],
      },
      {
        type: "error",
        name: "WrongPassword",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
      {
        type: "error",
        name: "ZeroAsset",
        inputs: [],
      },
    ],
    deployedOnBlock: 10812746,
  },
} as const;

export const CipherGift = {
  ...REMOTE,
  ...CipherGift_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
