/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialETHVault.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialETHVault } from "~~/contracts/ConfidentialETHVault";`
 */
import { ConfidentialETHVault as ConfidentialETHVault_LOCAL } from "./ConfidentialETHVault.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  1: {
    address: "0x01B008Ed2fA95858D9bfB730F58B5a49fA77b588",
    abi: [
      {
        type: "constructor",
        inputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "receive",
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "CANCEL_DELAY",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "SCALE",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "cancelWithdrawRequest",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "depositETH",
        inputs: [],
        outputs: [],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "fulfillWithdraw",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "decryptionProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "hasPendingWithdrawal",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "internalCredit",
        inputs: [
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "internalDebit",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "internalTransfer",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "orchestrator",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingWithdrawalIdOf",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingWithdrawals",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
          {
            name: "requestedAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "balanceHandle",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "requestWithdraw",
        inputs: [],
        outputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setOrchestrator",
        inputs: [
          {
            name: "newOrchestrator",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Deposited",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "weiAmount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "units",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "OrchestratorSet",
        inputs: [
          {
            name: "orchestrator",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PublicDecryptionVerified",
        inputs: [
          {
            name: "handlesList",
            type: "bytes32[]",
            indexed: false,
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            indexed: false,
            internalType: "bytes",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawCancelled",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawFulfilled",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "units",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
          {
            name: "weiAmount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawRequested",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "balanceHandle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "CancelTooEarly",
        inputs: [],
      },
      {
        type: "error",
        name: "CleartextOverflow",
        inputs: [],
      },
      {
        type: "error",
        name: "InsufficientPool",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidKMSSignatures",
        inputs: [],
      },
      {
        type: "error",
        name: "MalformedCleartext",
        inputs: [],
      },
      {
        type: "error",
        name: "NoPendingWithdrawal",
        inputs: [],
      },
      {
        type: "error",
        name: "NotGweiAligned",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOrchestrator",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "NotRequestOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "OrchestratorAlreadySet",
        inputs: [],
      },
      {
        type: "error",
        name: "PendingWithdrawalExists",
        inputs: [],
      },
      {
        type: "error",
        name: "TransferFailed",
        inputs: [],
      },
      {
        type: "error",
        name: "UninitializedBalance",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
      {
        type: "error",
        name: "ZeroValue",
        inputs: [],
      },
    ],
    deployedOnBlock: 0,
  },
  11155111: {
    address: "0x2D32FBb47c9A52264d1d954f98277Cd5f5830fBb",
    abi: [
      {
        type: "constructor",
        inputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "receive",
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "CANCEL_DELAY",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "SCALE",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "cancelWithdrawRequest",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "depositETH",
        inputs: [],
        outputs: [],
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "fulfillWithdraw",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "decryptionProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "hasPendingWithdrawal",
        inputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "internalCredit",
        inputs: [
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "internalDebit",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "internalTransfer",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "orchestrator",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingWithdrawalIdOf",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pendingWithdrawals",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
          {
            name: "requestedAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "balanceHandle",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "requestWithdraw",
        inputs: [],
        outputs: [
          {
            name: "reqId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setOrchestrator",
        inputs: [
          {
            name: "newOrchestrator",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Deposited",
        inputs: [
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "weiAmount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "units",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "OrchestratorSet",
        inputs: [
          {
            name: "orchestrator",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PublicDecryptionVerified",
        inputs: [
          {
            name: "handlesList",
            type: "bytes32[]",
            indexed: false,
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            indexed: false,
            internalType: "bytes",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawCancelled",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawFulfilled",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "units",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
          {
            name: "weiAmount",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WithdrawRequested",
        inputs: [
          {
            name: "reqId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "user",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "balanceHandle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "CancelTooEarly",
        inputs: [],
      },
      {
        type: "error",
        name: "CleartextOverflow",
        inputs: [],
      },
      {
        type: "error",
        name: "InsufficientPool",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidKMSSignatures",
        inputs: [],
      },
      {
        type: "error",
        name: "MalformedCleartext",
        inputs: [],
      },
      {
        type: "error",
        name: "NoPendingWithdrawal",
        inputs: [],
      },
      {
        type: "error",
        name: "NotGweiAligned",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOrchestrator",
        inputs: [],
      },
      {
        type: "error",
        name: "NotOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "NotRequestOwner",
        inputs: [],
      },
      {
        type: "error",
        name: "OrchestratorAlreadySet",
        inputs: [],
      },
      {
        type: "error",
        name: "PendingWithdrawalExists",
        inputs: [],
      },
      {
        type: "error",
        name: "TransferFailed",
        inputs: [],
      },
      {
        type: "error",
        name: "UninitializedBalance",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
      {
        type: "error",
        name: "ZeroValue",
        inputs: [],
      },
    ],
    deployedOnBlock: 10812745,
  },
} as const;

export const ConfidentialETHVault = {
  ...REMOTE,
  ...ConfidentialETHVault_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
